app:
  containerPort: 8080
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsUser: 101
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscale:
    enabled: true
